### ISSUE TITLE
Problems with _HOST notation for kerberos

### ISSUE THREAD

**Issue by domas** [naver/PyCQuery#6]
Let us assume you have:

- 2 hive servers: hiveserver1.local and hiverserver2.local
- zookeeper to handle loadbalancing to the working hiveserver instance.

In this situation you usually specify kerberos service like: 'hive/_HOST' and "_HOST" is replaced at the runtime, as only at the runtime you will get the information if you are going to connect to your hiveserver1.local or hiveserver2.local.

When I try to use '_HOST' notation as:

```
params = {
    'host': 'zk01.local, zk02.local, zk03.local',
    'port': '2181',
    'database': 'test_db',
    'is_zookeeper': True,
    'http_path': 'cliservice',
    'service_mode': 'http',
    'kerberos_service_name': 'hive/_HOST',
    'auth': 'KERBEROS',
    'username': "tester@MY.GREAT.REALM",
    'keytab_file': "/etc/security/keytabs/test.keytab",
    'krb_conf': conf.KerberosConf.from_file('/etc/krb5.conf')
}
```

This results in error: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/venv/python3.6/lib64/python3.6/site-packages/pycquery/hive.py", line 121, in connect
    return Connection(*args, **kwargs)
  File "/usr/local/venv/python3.6/lib64/python3.6/site-packages/pycquery/hive.py", line 283, in __init__
    self.set_auth_setting()
  File "/usr/local/venv/python3.6/lib64/python3.6/site-packages/pycquery/hive.py", line 394, in set_auth_setting
    tgs, enc, key = self.kerb_client.get_TGS(spn)
  File "/usr/local/venv/python3.6/lib64/python3.6/site-packages/pycquery_krb/client.py", line 269, in get_TGS
    rep = self.ksoc.sendrecv(req.dump())
  File "/usr/local/venv/python3.6/lib64/python3.6/site-packages/pycquery_krb/network/clientsocket.py", line 87, in sendrecv
    raise KerberosError(krb_message)
pycquery_krb.protocol.errors.KerberosError:  Error Code: 7 Reason: Server not found in Kerberos database
```

The workaround is config like this:

```
params = {
    'host': 'zk01.local, zk02.local, zk03.local',
    'port': '2181',
    'database': 'test_db',
    'is_zookeeper': True,
    'http_path': 'cliservice',
    'service_mode': 'http',
    'kerberos_service_name': 'hive/hiveserver1.local',
    'auth': 'KERBEROS',
    'username': "tester@MY.GREAT.REALM",
    'keytab_file': "/etc/security/keytabs/test.keytab",
    'krb_conf': conf.KerberosConf.from_file('/etc/krb5.conf')
}
```

But then I will only connect to hiveserver1 so there is no loadbalancing and no High Availability.

**Comment by Sunwoo-Shin** [comment]
Hi @domas, first of all, thanks for reporting this.

This issue was fixed in `1.0.4`.
